# Generated by Django 2.2.1 on 2020-02-25 16:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('net_name', models.CharField(max_length=30)),
                ('nodes', django_mysql.models.JSONField(default=dict)),
                ('edges', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=280)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
